spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: ${DB_PG_USERNAME:postgres}
    password: ${DB_PG_PASSWORD:1234}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 20
      auto-commit: false