spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lab_pessimistic?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_MYSQL_USERNAME:root}
    password: ${DB_MYSQL_PASSWORD:1234}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 20
      auto-commit: false